---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

x-docker-step: &docker-step
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    BUILD_TAG: ${DRONE_BRANCH}-${DRONE_COMMIT}
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD

x-docker-auth:
- &docker-auth docker login harbor.zyra.ca -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


steps:
- name: Build docker image
  <<: *docker-step
  commands:
  - docker build -t docker.pkg.github.com/zyra/autonats/autonats:$BUILD_TAG .

- name: Push docker image
  <<: *docker-step
  commands:
  - *docker-auth
  - docker push docker.pkg.github.com/zyra/autonats/autonats:$BUILD_TAG

- name: Push latest docker image
  <<: *docker-step
  when:
    branch:
    - master
  commands:
  - *docker-auth
  - docker tag docker.pkg.github.com/zyra/autonats/autonats:$BUILD_TAG docker.pkg.github.com/zyra/autonats/autonats:latest
  - docker push docker.pkg.github.com/zyra/autonats/autonats:latest

- name: Push version tagged image
  <<: *docker-step
  when:
    event:
    - tag
  commands:
  - *docker-auth
  - docker tag docker.pkg.github.com/zyra/autonats/autonats:$BUILD_TAG docker.pkg.github.com/zyra/autonats/autonats:$DRONE_TAG
  - docker push docker.pkg.github.com/zyra/autonats/autonats:$DRONE_TAG


- name: Build binaries
  image: golang:1.12-alpine
  when:
    event:
    - tag
  commands:
  - apk add git make
  - make build -j$(nproc)

- name: Publish binaries to Github
  image: plugins/github-release
  when:
    event:
    - tag
  settings:
    api_key:
      from_secret: github_secret
    files:
    - bin/autonats_darwin_amd64
    - bin/autonats_linux_amd64
    - bin/autonats_windows_amd64.exe
    checksum:
    - md5
    - sha1
    - sha256
    - sha512
---
kind: signature
hmac: 5a66776e4de503ec51fff4d4dfe4302aa6f7928baf887e7a1dd9c009a4f4cc37

...
